src/Entity/Grade.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GradeRepository")
 */
class Grade
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $note;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Student", inversedBy="grades")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Student;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Matter", inversedBy="grades")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Matter;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getStudent(): ?Student
    {
        return $this->Student;
    }

    public function setStudent(?Student $Student): self
    {
        $this->Student = $Student;

        return $this;
    }

    public function getMatter(): ?Matter
    {
        return $this->Matter;
    }

    public function setMatter(?Matter $Matter): self
    {
        $this->Matter = $Matter;

        return $this;
    }
}

templates/_grade_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{{ form_start(form, {method: 'POST', action: path('grade_create', {'student_id': student.id})}) }}
{{ form_widget(form) }}
{{ form_end(form) }}

templates/base.html.twig
<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %}UbiTest{% endblock %}</title>
    <script src="https://kit.fontawesome.com/5592f0e2de.js"></script>
    {% block stylesheets %}{% endblock %}
</head>
<body>
<div class="container-fluid">
    <div class="nav nav-fluid">
        <a href="{{ path('homepage') }}">Accueil</a>
    </div>
    {% block body %}{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% block javascripts %}{% endblock %}
</body>
</html>

templates/create.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block body %}
    <h3>Ajout d'un élève</h3>
    <div class="row">
        <div class="col-6">
            {{ form(form) }}
        </div>
    </div>
{% endblock %}

{% block stylesheets %}
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block javascripts %}
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<script src="https://unpkg.com/gijgo@1.9.13/js/messages/messages.fr-fr.js" type="text/javascript"></script>
    <script>
        var today = new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate());
        $('#student_birthdate').datepicker({
            uiLibrary: 'bootstrap4',
            format: 'dd/mm/yyyy',
            locale: 'fr-fr',
            weekStartDay: 1,
            maxDate: today,
            minDate: '01/01/1900',
        });
    </script>
{% endblock %}

templates/edit.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block body %}
    <h3>Edition d'un élève</h3>
    <div class="row">
        <div class="col-6">
            {{ form(form) }}
        </div>
        <div class="col-6">
            {% for message in app.flashes('success') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
            {% for message in app.flashes('error') %}
                <div class="alert alert-danger">
                    {{ message }}
                </div>
            {% endfor %}

            <h4>Notes</h4>
            {% if grades is defined and grades|length > 0 %}
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Matiere</th>
                        <th>Note</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for grade in grades %}
                        <tr>
                            <td>{{ grade.matter }}</td>
                            <td>{{ grade.note }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                Pas de note
            {% endif %}
            {{ render(controller('App\\Controller\\GradeController::gradeForm', {'id': student.id})) }}
        </div>
    </div>
{% endblock %}

{% block stylesheets %}
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block javascripts %}
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <script src="https://unpkg.com/gijgo@1.9.13/js/messages/messages.fr-fr.js" type="text/javascript"></script>
    <script>
        var today = new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate());
        $(function() {
            $('#student_birthdate').datepicker({
                uiLibrary: 'bootstrap4',
                format: 'dd/mm/yyyy',
                locale: 'fr-fr',
                weekStartDay: 1,
                maxDate: today,
                minDate: '01/01/1900',
            })
        });
    </script>
{% endblock %}

templates/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h3>Liste des élèves</h3>

    {% if students|length > 0 %}
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Prénom</th>
                <th scope="col">Nom</th>
                <th scope="col">Date de naissance</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
                {% for student in students %}
                    <tr>
                        <td>{{ student.id }}</td>
                        <td>{{ student.firstname }}</td>
                        <td>{{ student.lastname }}</td>
                        <td>{{ student.birthdate|date("d/m/Y") }}</td>
                        <td>
                            <a href="{{ path('student_edit', {'id': student.id}) }}" class="btn btn-info"><i class="fa fa-edit"></i> </a>
                            <a href="{{ path('student_delete', {'id': student.id}) }}" class="btn btn-danger"><i class="fa fa-trash-alt"></i> </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        Il n'y a pas d'élève enregistré
    {% endif %}

    <br>
    <a class="btn btn-primary" href="{{ path('student_create') }}">Ajouter un élève</a>
{% endblock %}